[package]
name = "publicworks-extension-permissions"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
publicworks-agent = { path = "../../agent", version = "0.1.0" }

[dev-dependencies]
futures-lite = "2"
publicworks-runtime = { path = "../../runtime" }
publicworks-storage-sqlite = { path = "../../storage/sqlite" }
serde_json = "1"
